package templater

import (
	"fmt"
	"strings"

	"github.com/merzzzl/golangarch-lint/internal/config"
)

// Run renders architecture instructions for an AI agent, not serialized YAML.
func (s *Service) Run() string {
	var sb strings.Builder
	sb.WriteString("# GOLANGARCH\n\n")
	sb.WriteString("Architecture instructions generated from .golangarch.yml. Follow these rules when creating, moving or editing Go code.\n")
	sb.WriteString("Do not edit this file manually; regenerate it with golangarch-lint docs. Verify changes with golangarch-lint lint .\n\n")
	sb.WriteString("## General instructions\n\n")
	sb.WriteString("- Keep package names equal to their directory names. Package main and the project root package are exempt.\n")
	sb.WriteString("- Keep every directory containing Go files covered by an architecture rule. Test files are ignored by the linter.\n")
	sb.WriteString("- Apply a matching file rule instead of its directory rule; do not inherit constraints from the replaced rule.\n")
	sb.WriteString("- Treat all path and ignore patterns as relative to the project root. A single star matches within one path segment; a double star spans any depth.\n")
	sb.WriteString("- Apply declaration permissions independently of layout, signatures, imports and calls. Allowing a name does not exempt it from any other check.\n")
	sb.WriteString("- Where both allow and deny lists exist, enforce the deny list first. An omitted allow list is unrestricted; an empty allow list allows nothing except the documented standard-library exemptions.\n")
	sb.WriteString("- Resolve interface calls to possible concrete implementations when checking direct call targets. Do not attribute calls inside a service to its caller: usecase -> service -> repos is allowed when each direct transition is permitted. Builtins are not package calls.\n")
	sb.WriteString("- Treat errors as failures. Report consolidation suggestions and unresolved call targets as warnings; warnings do not fail the command. Call analysis covers the current build environment, may overapproximate targets, and cannot fully resolve reflection or unsafe behavior.\n\n")
	sb.WriteString("## Rules per path\n")

	for i := range s.cfg.Rules {
		s.writeRule(&sb, &s.cfg.Rules[i])
	}

	return sb.String()
}

func (s *Service) writeRule(sb *strings.Builder, r *config.Rule) {
	fmt.Fprintf(sb, "\n### `%s`\n\n", r.Scope.Path)

	if len(r.Scope.Ignore) > 0 {
		fmt.Fprintf(sb, "- Skip this rule for paths matching %s and descendants of matching directories. Do not fall back to the replaced directory rule. Ignored code may still be loaded for type and call analysis.\n", s.formatList(r.Scope.Ignore))
	}

	if r.Layout.Directories.Flat != nil && !*r.Layout.Directories.Flat {
		sb.WriteString("- Do not put Go source files directly in this directory.\n")
	} else {
		sb.WriteString("- Go source files may be placed directly in this directory.\n")
	}

	if r.Layout.Directories.Subdirs != nil && !*r.Layout.Directories.Subdirs {
		sb.WriteString("- Do not create subdirectories.\n")
	} else {
		sb.WriteString("- Subdirectories are allowed.\n")
	}

	if r.Layout.Filenames != nil {
		if len(*r.Layout.Filenames) == 0 {
			sb.WriteString("- Do not create Go source files in this scope.\n")
		} else {
			fmt.Fprintf(sb, "- Every non-ignored Go source filename must match at least one of %s. Each pattern must match at least one file in each matched directory, including empty directories. Patterns match basenames; test files are excluded.\n", s.formatList(*r.Layout.Filenames))
		}
	}

	s.writeLayout(sb, r.Layout)

	for _, entry := range []struct {
		name  string
		value config.Visibility
	}{
		{"types", r.Declarations.Types},
		{"package-level variables", r.Declarations.Vars},
		{"constants", r.Declarations.Consts},
		{"functions and methods", r.Declarations.Funcs},
	} {
		s.writeDeclarations(sb, "exported "+entry.name, entry.value.Exported)
		s.writeDeclarations(sb, "unexported "+entry.name, entry.value.Unexported)
	}

	s.writeDependencies(sb, "Import", r.Imports)
	s.writeDependencies(sb, "Directly call implementations from", r.Imports)
	s.writeSignature(sb, "exported", r.Signatures.Exported)
	s.writeSignature(sb, "unexported", r.Signatures.Unexported)
}

func (*Service) writeLayout(sb *strings.Builder, layout config.Layout) {
	modes := layout.Binding.Modes()

	if len(modes) == 0 {
		sb.WriteString("- Declaration-to-filename binding is disabled for this scope.\n")

		return
	}

	if len(modes) == 1 && modes[0] == "single" {
		sb.WriteString("- Put at most one top-level declaration in each file: function, method, type, variable or constant. Each name in a grouped declaration counts separately. Imports, fields, interface methods and local declarations do not count. No filename binding is required.\n")

		return
	}

	if len(modes) > 1 {
		sb.WriteString("- Organize each whole file according to at least one of the following layouts. Do not mix layouts declaration by declaration to bypass a rule.\n")
	}

	for _, mode := range modes {
		if mode == "name" {
			sb.WriteString("- Name layout: put exported declarations (functions, methods, types, variables and constants) in files named after them (ReadModulePath -> read_module_path.go). Private declaration names must start with the normalized filename. Compare names ignoring case and underscores and stripping .go.\n")
			sb.WriteString("- Prefer consolidating name-layout files when all their declarations can share one existing filename without violating name binding. Unnecessary splitting produces a warning.\n")
		} else {
			sb.WriteString("- Receiver layout: declare a type in the file named after it (ExampleType -> example_type.go), and keep its receiver methods together there. Value, pointer and generic receivers are supported. All methods in a file must belong to the same type. Variable and constant names must start with that type name, ignoring case and underscores. Plain functions retain name binding.\n")
			sb.WriteString("- Coherent methods, variables and constants of the same type split across files produce a warning, provided the correctly named type declaration file exists in the package. Unrelated types, wrong receiver ownership and incorrectly named type declarations are errors.\n")
		}
	}

	sb.WriteString("- Consolidation suggestions apply only within this rule and matching build constraints. Preserve platform and build-tag separation.\n")
}

func (s *Service) writeDeclarations(sb *strings.Builder, label string, filter config.Filter) {
	if filter.Allow == nil && len(filter.Deny) == 0 {
		return
	}

	if filter.Allow != nil {
		if len(*filter.Allow) == 0 {
			fmt.Fprintf(sb, "- Do not declare any %s.\n", label)
		} else {
			fmt.Fprintf(sb, "- Declare %s only with names matching %s.\n", label, s.formatList(*filter.Allow))
		}
	}

	if len(filter.Deny) > 0 {
		fmt.Fprintf(sb, "- Do not declare %s with names matching %s, even if an allow pattern matches.\n", label, s.formatList(filter.Deny))
	}
}

func (s *Service) writeDependencies(sb *strings.Builder, verb string, filter config.Filter) {
	defaults := "standard-library packages"
	if verb == "Directly call implementations from" {
		defaults = "standard-library packages and the current package"
	}

	switch {
	case filter.Allow == nil:
		fmt.Fprintf(sb, "- %s any package unless explicitly forbidden below.\n", verb)
	case len(*filter.Allow) == 0:
		fmt.Fprintf(sb, "- %s %s only.\n", verb, defaults)
	default:
		fmt.Fprintf(sb, "- %s only packages matching %s; %s are also allowed.\n", verb, s.formatList(*filter.Allow), defaults)
	}

	if len(filter.Deny) > 0 {
		fmt.Fprintf(sb, "- Never %s packages matching %s, even if otherwise allowed.\n", strings.ToLower(verb), s.formatList(filter.Deny))
	}
}

func (s *Service) writeSignature(sb *strings.Builder, visibility string, sig config.Signature) {
	if sig.Receiver != nil {
		if *sig.Receiver {
			fmt.Fprintf(sb, "- Declare every %s function as a method with a receiver.\n", visibility)
		} else {
			fmt.Fprintf(sb, "- Declare %s functions without receivers; %s methods are forbidden.\n", visibility, visibility)
		}
	}

	for _, entry := range []struct {
		name  string
		allow *[]string
	}{{"parameters", sig.Inputs}, {"results", sig.Outputs}} {
		if entry.allow == nil {
			continue
		}

		if len(*entry.allow) == 0 {
			fmt.Fprintf(sb, "- Use only builtin and standard-library types in %s of %s functions and methods.\n", entry.name, visibility)
		} else {
			fmt.Fprintf(sb, "- In %s of %s functions and methods, use builtin/standard-library types or types matching %s (an exact package.Type or package-path pattern).\n", entry.name, visibility, s.formatList(*entry.allow))
		}
	}
}

func (*Service) formatList(items []string) string {
	quoted := make([]string, 0, len(items))
	for _, item := range items {
		quoted = append(quoted, "`"+item+"`")
	}

	return strings.Join(quoted, ", ")
}
