package templater

import (
	"fmt"
	"strings"
)

// Run renders an AI-oriented architecture instruction from the loaded config.
func (s *Service) Run() string {
	var sb strings.Builder

	sb.WriteString("# GOLANGARCH\n\n")
	sb.WriteString("Architecture instruction for this repository, generated from `.golangarch.yml` by golangarch-lint.\n")
	sb.WriteString("Follow these rules when creating, moving or editing Go code. Run `golangarch-lint lint .` to verify.\n")
	sb.WriteString("Do not edit this file manually — regenerate it with `golangarch-lint docs`.\n\n")

	s.runWriteUnconditional(&sb)
	s.runWriteIgnore(&sb)
	s.runWriteRules(&sb)

	return sb.String()
}

func (*Service) runWriteUnconditional(sb *strings.Builder) {
	sb.WriteString("## Always enforced (no configuration)\n\n")
	sb.WriteString("- Every exported function or method must live in a file named exactly after it: `ReadModulePath` -> `read_module_path.go` (normalization: lowercase, underscores removed, `.go` stripped).\n")
	sb.WriteString("- Every unexported function or method must live in a file whose normalized name is a prefix of the function name: `configValidateRule` may live in `config.go`.\n")
	sb.WriteString("- The package name must be exactly equal to its directory name (`package main` is exempt).\n")
	sb.WriteString("- Every directory containing `.go` files must be covered by at least one rule below.\n")
	sb.WriteString("- `*_test.go` files are always ignored by all checks.\n\n")
}

func (s *Service) runWriteIgnore(sb *strings.Builder) {
	if len(s.cfg.Ignore) == 0 {
		return
	}

	sb.WriteString("## Ignored paths (invisible to all checks)\n\n")

	for _, ig := range s.cfg.Ignore {
		fmt.Fprintf(sb, "- `%s`\n", ig)
	}

	sb.WriteString("\n")
}

func (s *Service) runWriteRules(sb *strings.Builder) {
	sb.WriteString("## Rules per path\n")
	sb.WriteString("\nRules with a file path (ending in `.go`) override directory rules for that file.\n")

	for i := range s.cfg.Rules {
		s.runWriteRule(sb, i)
	}
}

func (s *Service) runWriteRule(sb *strings.Builder, idx int) {
	r := &s.cfg.Rules[idx]

	fmt.Fprintf(sb, "\n### `%s`\n\n", r.Path)

	for _, ig := range r.Ignore {
		fmt.Fprintf(sb, "- Paths matching `%s` are exempt from this rule.\n", ig)
	}

	switch r.Mode {
	case "flat":
		sb.WriteString("- The directory must stay flat: subdirectories are forbidden.\n")
	case "subdirs-only":
		sb.WriteString("- The directory must contain only subdirectories: files are forbidden.\n")
	default:
	}

	s.runWriteAllow(sb, "types", r.AllowTypes, r.ExcludeTypes)
	s.runWriteAllow(sb, "package-level vars/consts", r.AllowVars, r.ExcludeVars)
	s.runWriteAllow(sb, "functions/methods", r.AllowFuncs, r.ExcludeFuncs)

	switch r.RequireReceiver {
	case "all":
		sb.WriteString("- Every function must be a method (declared with a receiver).\n")
	case "exported":
		sb.WriteString("- Every exported function must be a method (declared with a receiver).\n")
	case "local":
		sb.WriteString("- Every unexported function must be a method (declared with a receiver).\n")
	default:
	}

	if r.Exported != nil {
		if r.Exported.Inputs != nil {
			fmt.Fprintf(sb, "- Exported function parameters: stdlib types%s.\n", s.runFormatTypeList(r.Exported.Inputs))
		}

		if r.Exported.Outputs != nil {
			fmt.Fprintf(sb, "- Exported function results: stdlib types%s.\n", s.runFormatTypeList(r.Exported.Outputs))
		}
	}

	if r.Modules != nil {
		if len(r.Modules) == 0 {
			sb.WriteString("- Imports: stdlib only.\n")
		} else {
			fmt.Fprintf(sb, "- Imports: stdlib and %s only.\n", s.runFormatList(r.Modules))
		}
	}
}

func (s *Service) runWriteAllow(sb *strings.Builder, kind, mode string, excludes []string) {
	var phrase string

	switch mode {
	case "none":
		phrase = "no " + kind + " may be declared"
	case "local":
		phrase = "only unexported " + kind + " may be declared"
	case "exported":
		phrase = "only exported " + kind + " may be declared"
	default:
		return
	}

	if len(excludes) > 0 {
		phrase += ", except names matching " + s.runFormatList(excludes)
	}

	fmt.Fprintf(sb, "- Declarations: %s.\n", phrase)
}

func (s *Service) runFormatTypeList(patterns []string) string {
	if len(patterns) == 0 {
		return " only"
	}

	return " and types from " + s.runFormatList(patterns) + " only"
}

func (*Service) runFormatList(items []string) string {
	quoted := make([]string, 0, len(items))

	for _, it := range items {
		quoted = append(quoted, "`"+it+"`")
	}

	return strings.Join(quoted, ", ")
}
